name: SwiftLint

on:
  push:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '*.swift'

jobs:
  SwiftLint:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
        run: swiftlint --config .swiftlint.yml
