name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
  
    runs-on: macos-11.0
    
    steps:
    
      - uses: actions/checkout@v2
      
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_13.1.app
      
      - name: Run tests
        run: swift test -v
